### ISSUE TITLE
Unable to download certain posters

### ISSUE THREAD

**Issue by ytoaa** [ovear/kemono-dl#11] opened 2023-07-10 16:51 UTC
python3 "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono7/kemono-dl.py" --cookies "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono7/cookie.txt" --dirname-pattern  "home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono7/link/{username}@{user_id}/({published})Ch{id} {username}" --links https://kemono.party/patreon/user/7207629/post/35355619 --other-filename-pattern '({id}@@{filename}).{ext}'  --filename-pattern '({index}@@{filename}).{ext}' --inline --inline-filename-pattern "inline\({index}@@{filename}).{ext}" --content --comments --extract-links --skip-local-hash  && echo -e "\nSUCCESS."`date +\%Y\%m\%d`"\n"

INFO:Downloading posts from kemono.party.party | patreon | nekotewi | 7207629
ERROR:Unable to get posts for https://kemono.party/patreon/user/7207629/post/35355619
Traceback (most recent call last):
  File "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono7/src/main.py", line 699, in start_download
    self.get_post(url)
  File "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono7/src/main.py", line 165, in get_post
    post = self.clean_post(post, user, site)
  File "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono7/src/main.py", line 337, in clean_post
    content_soup = self.get_inline_images(new_post, content_soup)
  File "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono7/src/main.py", line 240, in get_inline_images
    inline_images = [inline_image for inline_image in content_soup.find_all("img") if inline_image['src'][0] == '/']
  File "/home/timi/ext/a/me/TEMPDOWNLOAD/PROGRAM/PYTHON/kemono7/src/main.py", line 240, in <listcomp>
    inline_images = [inline_image for inline_image in content_soup.find_all("img") if inline_image['src'][0] == '/']
  File "/home/timi/.local/lib/python3.10/site-packages/bs4/element.py", line 1519, in __getitem__
    return self.attrs[key]
KeyError: 'src'

**Comment by Ovear** [comment] 2023-07-10 16:59
Hmmm... This seems caused by malformed html.

**Comment by Ovear** [comment] 2023-07-10 18:06
Should fixed now, please ugrade to latest version.

**Closed as completed by Ovear** 2023-07-10 18:06 UTC
Labels: bug
